training:
  prefix: vow4_NL
  N_epochs: 15
  lr: 0.0004
  batch_size: 8
  max_samples: 216
  train_test_divide: 3
  use_cross_validation: false
data:
  sr: 10000
  gender: both
  vowels: 
    - ae
    - ei
    - iy
    - oa
geom:
  use_design_region: true
  use_rand_init: false
  Nx: 160
  Ny: 120
  dt: 0.707
  c0: 1.00
  c1: 0.80
  px: 
  py: 
  pd: 30
  src_x: 
  src_y:
  pml:
    N: 20
    p: 4.0
    max: 3.0
  nonlinearity:
    cnl: 0.0
    b0: 0.01
    uth: 0.1
  binarization:
    beta: 100
    eta: 0.5
